#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define ESP_UART_BYTE_TRACE   0

#define MODBUS_RECV_TIMEOUT_MS        500
#define MODBUS_CONNECT_TIMEOUT_MS     500

#define MODBUS_UART_PLC_FAIL_MIN_MS    4000
#define MODBUS_UART_ETH_DOWN_MIN_MS     5000
#define MODBUS_UART_SOCKET_FAIL_MIN_MS  8000
#define MODBUS_UART_IO_FAIL_MIN_MS       4000

#define STAGED_COMMAND_GUARD_MS         5000U

#define DEFAULT_TASK_VERBOSE_INTERVAL   5

#define APP_TELEMETRY_INTERVAL_MS       2000U

#endif
